#!/bin/sh -e
PREREQS=""
case $1 in
        prereqs) echo "${PREREQS}"; exit 0;;
esac
. /usr/share/initramfs-tools/hook-functions
#copy_modules_dir kernel/drivers/net/ethernet/broadcom
manual_add_modules bnx2x
